### ISSUE TITLE
surefire plugin declaration location in pom.xml of target project

### ISSUE THREAD

**Issue by DrRacket** [TestingResearchIllinois/starts#16]
'mvn starts:starts' failed on NonDex,  reporting 'project nondex: Surefire plugin not available' .
The surefire plugin is declared in the pom.xml of NonDex under \<project>\<build>\<pluginManagement>\<plugins>.
Adding surefire plugin under \<project>\<build>\<plugins> fixes this issue.
The sha for NonDex I'm working with is a1d2fa21e19acd5453abf4c549b61101ac115e3b.

**Comment by owolabileg** [comment]
Fixed in #40
