### ISSUE TITLE
Checkstyle triggered by STARTS when running on NonDex

### ISSUE THREAD

**Issue by DrRacket** [TestingResearchIllinois/starts#17]
'mvn starts:starts' failed on NonDex 'nondex-maven-plugin' module because checkstyle is triggered and the check failed the generated sources of the module.
The sha for NonDex I'm working with is a1d2fa21e19acd5453abf4c549b61101ac115e3b.

**Comment by owolabileg** [comment]
It is no longer clear if this issue persists, or how to fix it.
