### ISSUE TITLE
extract string constants to Constants.java

### ISSUE THREAD

**Issue by owolabileg** [TestingResearchIllinois/starts#24]
We have many `String` literals that are duplicated and scattered all over the codebase, e.g., `changed-classes`, `jar-checksums`, `all-tests`. The goal here is to refactor; move all these literals to `edu.illinois.starts.constants.StartsConstants`.

**Comment by jkhodadadian** [comment]
I am refactoring these many String literals, moving them to `edu.illinois.starts.constants.StartsConstants`.  I will submit a pull request in the next few days.

**Comment by jkhodadadian** [comment]
@owolabileg I submitted a PR that fixes this issue. I would be glad if you take a look at it!

**Comment by owolabileg** [comment]
Fixed in #30
