### ISSUE TITLE
migrate cleanup code from verifyutil to setuputil

### ISSUE THREAD

**Issue by cptwonton** [TestingResearchIllinois/starts#47]
in order for integration tests to work AND allow the user to look thru all available artifacts, the cleanup code that does stuff like deletefiles and deletefolders will need to be moved to setuputil and called from setup.groovy. they are currently in verifyutil and called from verify.groovy.

**Comment by owolabileg** [comment]
We unfortunately do not have the resources to tackle this request at this time.
