### ISSUE TITLE
No plugin found for prefix 'starts' locally and maven central

### ISSUE THREAD

**Issue by marufzaber** [TestingResearchIllinois/starts#65]
I included the plugin xml code as mentioned in the [read.me](https://github.com/TestingResearchIllinois/starts/blob/master/README.md) (as well as installed it from the source code) but couldn't get STARTS work with `mvn starts:starts`. I get the following ERROR - 

_`No plugin found for prefix 'starts' in the current project and in the plugin groups [org.apache.maven.plugins, org.codehaus.mojo] available from the repositories [local (/Users/<USERNAME>/.m2/repository), central (https://repo.maven.apache.org/maven2)]`_

However, I installed it from the source and used the following command instead  and it works wonder - 
`mvn edu.illinois:starts-maven-plugin:1.4-SNAPSHOT:starts`

Thought, you guys should know and update the read.me .

**Comment by august782** [comment]
Thank you for reporting this. I unfortunately cannot reproduce this, can you please share the project you are modifying, as well as the modified pom.xml?

Also, when you are modifying the pom.xml, are you using version 1.3 as written in the README or are you using another version?
