### ISSUE TITLE
Migrate to travis-ci.com

### ISSUE THREAD

**Issue by jtx1999** [TestingResearchIllinois/starts#84]
travis-ci.org will be deprecated.

**Comment by benjamin-shen** [comment]
Steps:
1. It seems like Travis CI changed their pricing model (https://www.travis-ci.com/pricing/) and now would require paid credits. Determine if we should continue using Travis CI or move away. Related posts: [curl](https://github.com/curl/curl/issues/7150), [earthly.dev](https://earthly.dev/blog/migrating-from-travis).
2. If we choose to migrate, a project maintainer would need to log in or create an account on travis-ci.com and connect the STARTS repository on the migration tab of the settings page (https://app.travis-ci.com/account/migrate), which will prompt an installation of the Travis CI application on all/select Github repositories (https://github.com/settings/installations/29866009). Then, builds will be enabled on https://app.travis-ci.com/github/TestingResearchIllinois/starts.
3. Update the [build status badge](https://github.com/TestingResearchIllinois/starts/blob/31cf392ace67ec3de0f825e910e706382650bece/README.md?plain=1#L3) from `.org` to `.com` in the project's main readme. There may need to be a new build triggered on the master branch.

**Comment by owolabileg** [comment]
We are deciding to move to GitHub Actions.
