### ISSUE TITLE
STARTS not working in JAVA 7

### ISSUE THREAD

**Issue by SZTankWang** [TestingResearchIllinois/starts#87]
Hi:
I am trying to integrate STARTS with defects4j, which is a project containing real-world java projects and real faults. To make `defects4j` work properly, it is suggested I use **java 7**. So what I do is this:
+ I checkout a new, uncompiled version using defects4j command
+ I run `mvn starts:select` to output the list of impacted tests.
Here comes the error:
```
[ERROR] Failed to execute goal edu.illinois:starts-maven-plugin:1.3:select (default-cli) on project commons-lang3: 
Execution default-cli of goal edu.illinois:starts-maven-plugin:1.3:select failed: 
An API incompatibility was encountered while executing edu.illinois:starts-maven-plugin:1.3:select: java.lang.UnsupportedClassVersionError: edu/illinois/yasgl/DirectedGraph : Unsupported major.minor version 52.0
```
+ `echo $JAVA_HOME` : /usr/lib/jvm/jdk1.7.0_80
+ `java -version: java version "1.7.0_80"`

Previously, I use **java 8** and everything about STARTS was fine, however, there appears that some of the developer-written test in defects4j will broken and turned out failed. 
Is there any suggestion here ? 

Regards,
Zhenming

**Comment by owolabileg** [comment]
Thanks for your interest in STARTS, Zhenming! At this time, STARTS only works on Java 1.8 and above, as stated in the README.
